### ISSUE TITLE
Self hosted docker instance Accesskey is expired when I create it

### ISSUE THREAD

**Issue by Hypnos3** [kservices/gBridge#18] opened 2018-11-29 10:28 UTC
If I create a accesskey the key is already expired.

The Valid until timestamp is the timestamp of pushing the add accesskey button.

**Comment by peterkappelt** [comment] 2018-11-29 15:19
Duplicate of #4. 
Should be fixed with the current release. Are you using the newest version of the Docker containers?

**Comment by Hypnos3** [comment] 2018-11-29 21:54
I have installed yesterday.
How to update the docker container or need to reinstall?

**Comment by peterkappelt** [comment] 2018-12-15 16:41
Sorry for answering late.
Try the following procedure for update:
```
docker-compose stop
docker-compose pull web
docker-compose pull redis-worker
docker-compose up
```

**Closed as completed** 2018-12-30 09:11 UTC
