### ISSUE TITLE
Unable to link to gBridge using new Google Home App

### ISSUE THREAD

**Issue by vanceb** [kservices/gBridge#9] opened 2018-10-21 17:40 UTC
I did originally manage to link my google account to gBridge, but had to change accounts.  Since the original account linking there has been a new version of the Google Home app which has a different interface. These [instructions](https://doc.gbridge.kappelt.net/html/firstSteps/gettingStarted.html) are no longer correct.

To add the gBridge service you now need to navigate:

`Main Home Screen -> Add -> Set up Device -> Works with Google -> Search for gBridge`

Trying to add the service by putting in my email address and the Access Key looks to authenticate, but then fails with a brief error message "Could not update settings, check connection"

The gBridge app is not linked to the phone and I cannot see any of my devices.  I have attempted this a number of times generating a new Access Key for each attempt.  still no success.

**Comment by vanceb** [comment] 2018-10-21 17:55
Looks like this may be a [common issue](https://www.reddit.com/r/googlehome/comments/7npsz8/psa_solutions_to_the_couldnt_update_the_settings/) with Google Home.  

I am going to attempt to remove all my devices, relink the account, then add back the devices...

This didn't work!  I could still not add gBridge to the Google Home app.

**Comment by vanceb** [comment] 2018-10-21 18:04
Problam looks like it is to do with the browser authentication.  I was signed into Chrome with a different  Google account to the one I was trying to add gBridge to.  I changed my default browser to firefox and retried the linking.  As I had just installed firefox it first asked me to log into the google account - I now used the one associated with the Google Home app and the phone was able to link gBridge into the Google Home app

So this looks like an authentication issue for people who have more than one Google account...

**Comment by peterkappelt** [comment] 2018-10-21 20:44
I can reproduce this issue for my setup. However, the devices of my gBridge account still appear after account linking, even though the error message is shown.

Thanks for your investigation and research! I'm going to have a closer look at it and I'll eventuelle prépare a workaround/ statement for gBridge users

**Comment by vanceb** [comment] 2018-10-22 11:30
I was just trying the potential resolutions from the [Reddit](https://www.reddit.com/r/googlehome/comments/7npsz8/psa_solutions_to_the_couldnt_update_the_settings/) conversation.  I don't think deleting and recreating the devices had any effect.  

I think the key problem is Chrome tries to authenticate with the main account used on the Android device.  For me this is a G-Suite account which doesn't allow me to invite others to join the "Home", so I had to use standard gmail accounts to be able to share with my family, but this meant that the Google Home account I was trying to authorise gBridge to use was different to the one Chrome was using.  The error message it throws when it fails isn't very useful, and disappears quickly.  You might not notice the error message, but you won't see your devices...

**Comment by peterkappelt** [comment] 2018-11-08 16:17
I've just linked the Reddit conversation in the documentation.

I'm unable to fix it, since it has absolutely nothing to do with any of my implementation. We need to wait for Google to finally fix it...

Gonna close it for now, please re-open or comment if you've got any news (before I got them)

**Comment by peterkappelt** [comment] 2018-11-18 17:49
Has anyone got recent updates on this issue?

I'm currently unable to link the account of my own development server :worried: :cry:...
The mentioned workaround doesn't work for me. I can't get in touch with Google about this issue...

**Comment by giejay** [comment] 2018-11-19 18:45
Not really helpful but I linked my account just yesterday and it went fine, using Android 8 with latest Google Home app and Chrome browser.

**Comment by peterkappelt** [comment] 2018-11-24 15:01
Worked for me the next day, again 😕 

Thanks for nothing, Google...

**Closed by peterkappelt** 2018-11-24 15:01 UTC
